export interface IconEntry {
  icon: string
  label: string
}

export const ACTION_ICON_LIBRARY: IconEntry[] = [
  { icon: "tabler:sparkles", label: "Sparkles" },
  { icon: "tabler:wand", label: "Wand" },
  { icon: "tabler:brain", label: "Brain" },
  { icon: "tabler:robot", label: "Robot" },
  { icon: "tabler:bulb", label: "Bulb" },
  { icon: "tabler:flask", label: "Flask" },
  { icon: "tabler:star", label: "Star" },
  { icon: "tabler:stars", label: "Stars" },
  { icon: "tabler:cpu", label: "CPU" },
  { icon: "tabler:cpu-2", label: "CPU" },
  { icon: "tabler:language", label: "Translate" },
  { icon: "tabler:alphabet-latin", label: "Alphabet" },
  { icon: "tabler:article", label: "Article" },
  { icon: "tabler:edit", label: "Edit" },
  { icon: "tabler:pencil", label: "Pencil" },
  { icon: "tabler:typography", label: "Typography" },
  { icon: "tabler:align-left", label: "Align" },
  { icon: "tabler:file-text", label: "File Text" },
  { icon: "tabler:copy", label: "Copy" },
  { icon: "tabler:scissors", label: "Scissors" },
  { icon: "tabler:clipboard", label: "Clipboard" },
  { icon: "tabler:bold", label: "Bold" },
  { icon: "tabler:italic", label: "Italic" },
  { icon: "tabler:underline", label: "Underline" },
  { icon: "tabler:strikethrough", label: "Strikethrough" },
  { icon: "tabler:quote", label: "Quote" },
  { icon: "tabler:message-circle", label: "Chat" },
  { icon: "tabler:message", label: "Message" },
  { icon: "tabler:messages", label: "Messages" },
  { icon: "tabler:mail", label: "Mail" },
  { icon: "tabler:send", label: "Send" },
  { icon: "tabler:thumb-up", label: "Like" },
  { icon: "tabler:thumb-down", label: "Dislike" },
  { icon: "tabler:at", label: "At Sign" },
  { icon: "tabler:hash", label: "Hash" },
  { icon: "tabler:phone", label: "Phone" },
  { icon: "tabler:search", label: "Search" },
  { icon: "tabler:zoom-question", label: "Question" },
  { icon: "tabler:chart-bar", label: "Chart" },
  { icon: "tabler:eye", label: "View" },
  { icon: "tabler:report-analytics", label: "Analytics" },
  { icon: "tabler:help-circle", label: "Help" },
  { icon: "tabler:info-circle", label: "Info" },
  { icon: "tabler:filter", label: "Filter" },
  { icon: "tabler:sort-ascending", label: "Sort" },
  { icon: "tabler:list-search", label: "List Search" },
  { icon: "tabler:code", label: "Code" },
  { icon: "tabler:terminal", label: "Terminal" },
  { icon: "tabler:bug", label: "Bug" },
  { icon: "tabler:git-branch", label: "Branch" },
  { icon: "tabler:server", label: "Server" },
  { icon: "tabler:database", label: "Database" },
  { icon: "tabler:brackets", label: "Brackets" },
  { icon: "tabler:terminal-2", label: "Terminal" },
  { icon: "tabler:command", label: "Command" },
  { icon: "tabler:variable", label: "Variable" },
  { icon: "tabler:arrow-right", label: "Arrow" },
  { icon: "tabler:check", label: "Check" },
  { icon: "tabler:x", label: "Close" },
  { icon: "tabler:refresh", label: "Refresh" },
  { icon: "tabler:download", label: "Download" },
  { icon: "tabler:share", label: "Share" },
  { icon: "tabler:bookmark", label: "Bookmark" },
  { icon: "tabler:heart", label: "Heart" },
  { icon: "tabler:external-link", label: "External Link" },
  { icon: "tabler:link", label: "Link" },
  { icon: "tabler:home", label: "Home" },
  { icon: "tabler:menu", label: "Menu" },
  { icon: "tabler:chevron-right", label: "Chevron Right" },
  { icon: "tabler:chevron-left", label: "Chevron Left" },
  { icon: "tabler:arrow-left", label: "Arrow Left" },
  { icon: "tabler:arrow-up", label: "Arrow Up" },
  { icon: "tabler:arrow-down", label: "Arrow Down" },
  { icon: "tabler:compass", label: "Compass" },
  { icon: "tabler:map", label: "Map" },
  { icon: "tabler:route", label: "Route" },
  { icon: "tabler:folder", label: "Folder" },
  { icon: "tabler:file", label: "File" },
  { icon: "tabler:trash", label: "Trash" },
  { icon: "tabler:archive", label: "Archive" },
  { icon: "tabler:book", label: "Book" },
  { icon: "tabler:note", label: "Note" },
  { icon: "tabler:calendar", label: "Calendar" },
  { icon: "tabler:clock", label: "Clock" },
  { icon: "tabler:tag", label: "Tag" },
  { icon: "tabler:user", label: "User" },
  { icon: "tabler:users", label: "Users" },
  { icon: "tabler:globe", label: "Globe" },
  { icon: "tabler:lock", label: "Lock" },
  { icon: "tabler:unlock", label: "Unlock" },
  { icon: "tabler:key", label: "Key" },
  { icon: "tabler:shield", label: "Shield" },
  { icon: "tabler:alert-circle", label: "Alert" },
  { icon: "tabler:alert-triangle", label: "Warning" },
  { icon: "tabler:loader", label: "Loader" },
  { icon: "tabler:image", label: "Image" },
  { icon: "tabler:camera", label: "Camera" },
  { icon: "tabler:play", label: "Play" },
  { icon: "tabler:pause", label: "Pause" },
  { icon: "tabler:volume", label: "Volume" },
  { icon: "tabler:headphones", label: "Headphones" },
  { icon: "tabler:settings", label: "Settings" },
  { icon: "tabler:adjustments", label: "Adjustments" },
  { icon: "tabler:palette", label: "Palette" }
]
