import fs from "fs"
import path from "path"

// 104 default icons from ACTION_ICON_LIBRARY
const DEFAULT_ICONS = [
  "tabler:sparkles",
  "tabler:wand",
  "tabler:brain",
  "tabler:robot",
  "tabler:bulb",
  "tabler:flask",
  "tabler:star",
  "tabler:stars",
  "tabler:cpu",
  "tabler:cpu-2",
  "tabler:language",
  "tabler:alphabet-latin",
  "tabler:article",
  "tabler:edit",
  "tabler:pencil",
  "tabler:typography",
  "tabler:align-left",
  "tabler:file-text",
  "tabler:copy",
  "tabler:scissors",
  "tabler:clipboard",
  "tabler:bold",
  "tabler:italic",
  "tabler:underline",
  "tabler:strikethrough",
  "tabler:quote",
  "tabler:message-circle",
  "tabler:message",
  "tabler:messages",
  "tabler:mail",
  "tabler:send",
  "tabler:thumb-up",
  "tabler:thumb-down",
  "tabler:at",
  "tabler:hash",
  "tabler:phone",
  "tabler:search",
  "tabler:zoom-question",
  "tabler:chart-bar",
  "tabler:eye",
  "tabler:report-analytics",
  "tabler:help-circle",
  "tabler:info-circle",
  "tabler:filter",
  "tabler:sort-ascending",
  "tabler:list-search",
  "tabler:code",
  "tabler:terminal",
  "tabler:bug",
  "tabler:git-branch",
  "tabler:server",
  "tabler:database",
  "tabler:brackets",
  "tabler:terminal-2",
  "tabler:command",
  "tabler:variable",
  "tabler:arrow-right",
  "tabler:check",
  "tabler:x",
  "tabler:refresh",
  "tabler:download",
  "tabler:share",
  "tabler:bookmark",
  "tabler:heart",
  "tabler:external-link",
  "tabler:link",
  "tabler:home",
  "tabler:menu",
  "tabler:chevron-right",
  "tabler:chevron-left",
  "tabler:arrow-left",
  "tabler:arrow-up",
  "tabler:arrow-down",
  "tabler:compass",
  "tabler:map",
  "tabler:route",
  "tabler:folder",
  "tabler:file",
  "tabler:trash",
  "tabler:archive",
  "tabler:book",
  "tabler:note",
  "tabler:calendar",
  "tabler:clock",
  "tabler:tag",
  "tabler:user",
  "tabler:users",
  "tabler:globe",
  "tabler:lock",
  "tabler:lock-open",
  "tabler:key",
  "tabler:shield",
  "tabler:alert-circle",
  "tabler:alert-triangle",
  "tabler:loader",
  "tabler:photo",
  "tabler:camera",
  "tabler:play",
  "tabler:pause",
  "tabler:volume",
  "tabler:headphones",
  "tabler:settings",
  "tabler:adjustments",
  "tabler:palette"
]

// Additional nav icons not in the default 104
const NAV_ICONS = ["tabler:api", "tabler:database-export"]

// Combine all needed icons
const ALL_ICONS = [...new Set([...DEFAULT_ICONS, ...NAV_ICONS])]

// Read tabler.json from @iconify/json
const tablerJsonPath = path.resolve(process.cwd(), "node_modules/@iconify/json/json/tabler.json")
const tablerData = JSON.parse(fs.readFileSync(tablerJsonPath, "utf-8"))

// Extract only needed icons
const extractedIcons: Record<string, { body: string }> = {}
let foundCount = 0

for (const iconName of ALL_ICONS) {
  const name = iconName.replace("tabler:", "")
  if (tablerData.icons[name]) {
    extractedIcons[name] = { body: tablerData.icons[name].body }
    foundCount++
  } else {
    console.warn(`Warning: Icon "${iconName}" not found in tabler.json`)
  }
}

// Generate the bundled-icons.ts file
const outputContent = `// This file is auto-generated by scripts/bundle-icons.ts
// Do not edit manually
// Run "npm run bundle-icons" to regenerate

export const BUNDLED_TABLER_ICONS = {
  prefix: "tabler",
  icons: ${JSON.stringify(extractedIcons, null, 2)},
  width: 24,
  height: 24
}
`

const outputPath = path.resolve(process.cwd(), "src/shared/ui/bundled-icons.ts")
fs.writeFileSync(outputPath, outputContent, "utf-8")

console.log(`✓ Generated bundled-icons.ts with ${foundCount} icons`)
console.log(`  Output: ${outputPath}`)
